name       : riot
version    : 0.10.1
release    : 5
homepage   : https://riot.im/
source     :
    - https://github.com/vector-im/riot-web/archive/v0.10.1.tar.gz : e70b0bdf4801eeff86750af172d01d05029dc075b21fa758f5df338ef818e6a4
license    : Apache-2.0
component  : network.im
networking : yes
summary    : Electron based Matrix client built using the Matrix React SDK
description: |
    Riot is an electron based Matrix client that allows cross platform
    communication between IRC, slack, gitter and riot/matrix
    users.  Also has secure end to end encrypted chat through
    text, audio and video with users of riot/matrix on
    Android, iOS, Windows, OSX, Linux and web browsers.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-x11-2.0)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
rundeps    :
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-change-deb-to-dir-for-building.patch
    npm install
    cd electron_app
    npm install
build      : |
    npm run build
    node_modules/.bin/build -l --x64
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/riot
    cp -Rv electron_app/dist/linux-unpacked/* $installdir/usr/share/riot/
    ln -sv ../share/riot/riot-web $installdir/usr/bin/riot-web

    # Install Icons
    for icon_size in 16 24 48 64 96 128 256 512
    do
        install -D -m00644 electron_app/build/icons/${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/riot-web.png
    done

    # Desktop File
    rm -f $installdir/usr/share/applications/riot.desktop
    install -D -m00644 $pkgfiles/riot.desktop $installdir/usr/share/applications/riot.desktop
