name       : riot
version    : 0.17.8
release    : 23
homepage   : https://riot.im/
source     :
    - https://github.com/vector-im/riot-web/archive/v0.17.8.tar.gz : ded5fed8a967338bb43d6066b91aa67d039b76528d1be451274e4d9ef402db16
license    : Apache-2.0
component  : network.im
networking : yes
summary    : Electron based Matrix client built using the Matrix React SDK
description: |
    Riot is an electron based Matrix client that allows cross platform communication between IRC, slack, gitter and riot/matrix users. Also has secure end to end encrypted chat through text, audio and video with users of riot/matrix on Android, iOS, Windows, OSX, Linux and web browsers.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xtst)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
rundeps    :
    - nodejs
setup      : |
    npm install --no-shrinkwrap
build      : |
    npm run build
    node_modules/.bin/build -l --x64 --dir
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/riot
    cp -Rv electron_app/dist/linux-unpacked/* $installdir/usr/share/riot/
    ln -sv ../share/riot/riot-web $installdir/usr/bin/riot-web

    # Install Icons
    for icon_size in 16 24 48 64 96 128 256 512
    do
        install -Dm00644 electron_app/build/icons/${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/riot-web.png
    done

    # Desktop File
    install -Dm00644 $pkgfiles/riot.desktop $installdir/usr/share/applications/riot.desktop
